version: 1

disable_existing_loggers: true

loggers:
  "": # root logger
    level: INFO
    handlers: [ consoleHandler ]

handlers:
  consoleHandler:
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stdout

formatters:
  standard:
    format: "%(asctime)s %(levelname)-6s %(name)s %(funcName)s() %(message)s"
